### ISSUE TITLE
Different versions yield different ORFs

### ISSUE THREAD

**Issue by celiosantosjr** [althonos/pyrodigal#13]
Hi, I am trying pyrodigal using the following conditions:

    gorf = pyrodigal.OrfFinder(closed=True,
                               min_gene=33,
                               max_overlap=0)       

    morf_finder = pyrodigal.OrfFinder(meta=True,
                                      closed=True,
                                      min_gene=33,
                                      max_overlap=0)

When I test the system using different python versions (3.7, 3.8, 3.9) it gives me different ORFs for the same set of contigs.
Most of the ORFs are kept, however, in different versions of python sometimes the same couple of ORFs are and are not seen.
Do you have any idea of how to fix it or if this is an issue for the system?

PS.: To make sure it was not due to heuristics, I fixed the random.seed() in both processes and still got this variation, which is also not fixed to the version, as different runs in the same version eventually have different results even after seed.

**Comment by althonos** [comment]
Hi @celiosantosjr , are you using the `v0.7.2` version of Pyrodigal for all versions of Python? And when you say "sometimes", does it mean that on several runs of the same Python version it does produce inconsistent results?

This is probably not linked to the heuristics, as Prodigal doesn't use randomness anywhere to my knowledge. When I saw this happen earlier, this was due to uninitialized memory being accessed.

Do you have a FASTA file I could use as a basis for debugging? I have several test files and so far the issue never occurred (Pyrodigal and Prodigal 100% agree on these files) so maybe there's something special about the sequence.

**Comment by celiosantosjr** [comment]
Hi Martin,

Sure thing it may be some uninitialized values, however, I am using newly
created virtual environments in Conda to test it and the functions do not
contain any variable that could fall in this case. Indeed, it seems that it
is more often for python 3.8 and 3.7. I am using the following file:

```
https://github.com/BigDataBiology/macrel/blob/master/example_seqs/excontigs.fna.gz
```

Especially, the problem seems always related to the appearance or
disappearance of these two small ORFs:

| contig | start | end | strand | confidence | begin_partial | end_partial
| gc_cont | transl._table | start_codon |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
:---: |
| scaffold16564_1_MH0058 | 48 | 347 | 1 | 92.5139407832543 | FALSE | FALSE
| 0.453333333333333 | 11 | GTG |
| scaffold16564_1_MH0058 | 426 | 590 | 1 | 92.4551632549737 | FALSE | FALSE
| 0.393939393939394 | 11 | ATG |

Best,
Celio

**Comment by althonos** [comment]
When I said "uninitialized memory", I meant within Pyrodigal's Cython code, not in your environment :wink:  Thanks for the sequence, I'll have a look!

**Comment by althonos** [comment]
Okay, I think found the bug! It's actually a bug that originated from the Prodigal code that I ported in Cython: basically, after doing the dynamic programming round in _meta_ mode, it would not check that the resulting forward path was valid, and since invalid state is marked with `-1`, there was undefined behaviour caused by an out-of-bound access to the node memory. This is really an edge case and I don't think it can occur outside of `closed=True` parameterized searches, that's why I didn't catch it earlier.

After applying a fix it looks these two genes don't disappear anymore, at least after trying for quite some time. I'll push a new release with the patch, hopefully that'll fix it for you too.

**Comment by althonos** [comment]
Basically, in here: 

https://github.com/althonos/pyrodigal/blob/e08f501452f490e16bfafc3adb2c218b59fd85e6/pyrodigal/_pyrodigal.pyx#L4336-L4374

When checking the `if` condition, there's a possibility that `ipath` is `-1`, which causes accessing `nodes[-1]`, which can contain anything because it's outside of the allocated memory. In the event where `nodes[-1].score` (which is random memory) is higher than `max_score`, then it fucked up the search for the highest scoring phase.

**Comment by celiosantosjr** [comment]
Thank you. I will wait for your new version to implement pyrodigal elsewhere.

**Comment by althonos** [comment]
New release `v0.7.3` is out on PyPI :smiley:
