### ISSUE TITLE
[2.3.0] Build fails: 'cpython/unicode/PyUnicode_New.pxd' not found, etc

### ISSUE THREAD

**Issue by yurivict** [althonos/pyrodigal#40]
[Here](https://people.freebsd.org/~yuri/pyrodigal-2.3.0-build-failure.txt) is a complete log.

Python-3.9
cython-0.29.36
FreeBSD 13.2

**Comment by althonos** [comment]
Hi @yurivict,

In `2.3.0` I updated Pyrodigal to use Cython 3.0, so you will have to update the build recipe on your end for it to build fine.

**Comment by oschwengers** [comment]
Maybe related, but due to https://anaconda.org/bioconda/pyrodigal/files, since `v2.2.0` Pyrodigal is only available for Python `3.11`. Since other tools that are often used in combined conda envs with Pyrodigal are not (yet) available for Python `3.11` it would be nice if this could be somehow fixed.

**Comment by yurivict** [comment]
This works, thanks!
