### ISSUE TITLE
Some tests are skipped 'requires machine with SSE2 support' on the system which does have SSE2

### ISSUE THREAD

**Issue by yurivict** [althonos/pyrodigal#49]
```
test_score_connections_final (pyrodigal.tests.test_connection_scorer.TestConnectionScorerSSE) ... skipped 'requires machine with SSE2 support'
test_score_connections_train (pyrodigal.tests.test_connection_scorer.TestConnectionScorerSSE) ... skipped 'requires machine with SSE2 support'
```

The CPU is a regular Intel CPU: Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz

Version: 3.2.1
Pythoion-3.9
FreeBSD 13.2

**Comment by althonos** [comment]
I made a patch so that SSE2 is always turned on for x86-64 CPUs, since it's part of the AMD64 specification. The issue with runtime detection is probably coming from the [`archspec`](https://github.com/archspec/archspec) library, which is used to check CPU capabilities at runtime. Please open an issue report there if you identify problems on FreeBSD!
